[mat4]
# Cyan
shades = [3, 3, 28, 28, 29, 29, 29, 8, 8]

[mat8]
# Red
shades = [15, 9, 10, 12, 12, 12, 12, 13, 14]

[mat21]
# White
shades = [4, 5, 6, 7, 7, 7, 8, 8, 8]

[mat23]
# Black
shades = [0, 0, 0, 1, 1, 1, 2, 2, 2]
